Areas/Admin/Controllers/Dashb1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestionAbscences.Data;
using GestionAbscences.Models;
using System.Data.Entity;

using GestionAbscences.Areas.Admin.Models;
using System.Web.Helpers;
using System.Web.UI;
using System.Windows.Forms.DataVisualization.Charting;

namespace GestionAbscences.Areas.Admin.Controllers
{
    public class Dashb1Controller : Controller
    {
        // GET: Admin/Dashb1
        private GestionAbscencesEntities11 db = new GestionAbscencesEntities11();
        // GET: DashB
        public ActionResult Index()
        {

            int[] tab = new int[] { };

            int i = 0;
            var entites = db.entite.ToList();
            foreach (var item in entites)
            {
                int somme = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.typeconge.designation == "2eme tranche" && p.employe.affectation == item.Designation).Count();

                tab[i] = 1;

                i = i + 1;
               

            }

            Session["test"] = tab.Length.ToString();

            string x = Session["matricule"].ToString();
            //global
            var count1 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Count();
            Session["global"] = count1.ToString();

            var test = count1.ToString();
            if(test.Equals("0"))
            {
                Session["accept1"] = 0;
                Session["refuse1"] = 0;
                Session["enCours1"] = 0;

            }
            else
            {
                //accepte
                var count2 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p =>  p.ValdationRH == "accepte").Count();
                Session["accepte"] = count2.ToString();
                var num1 = count2 * 100;
                Session["accept1"] = num1 / count1;
                //refuse
                var count3 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p =>  (p.ValdationRH == "refuse" || p.ValidationN1 == "refuse" || p.ValidationN2 == "refuse")).Count();
                Session["refuse"] = count3.ToString();
                var num2 = count3 * 100;
                Session["refuse1"] = num2 / count1;
                //encours
                var count4 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => (p.ValdationRH == "En cours" || p.ValidationN1 == "En cours" || p.ValidationN2 == "En cours")).Count();
                Session["enCours"] = count4.ToString();
                var num3 = count4 * 100;
                Session["enCours1"] = num3 / count1;
           
            }

            return View(entites);
        }
        public ActionResult Global()
        {
            //employe e = new employe();
            Session["Message"] = null;

            string x = Session["matricule"].ToString();

            // int x1 = int.Parse(x);


            var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).OrderByDescending(news => news.DateDC).ToList();



            //  var t = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.employe.matricule == x).Count();
            //ViewBag.count = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.employe.matricule == x).Count().ToString();
            return View(demandeConge);

        }
        public ActionResult Accepte()
        {
            //employe e = new employe();
            Session["Message"] = null;

            string x = Session["matricule"].ToString();

            // int x1 = int.Parse(x);


            var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p =>  p.ValdationRH == "accepte").OrderByDescending(news => news.DateDC).ToList();


            return View(demandeConge);

        }
        public ActionResult Refuse()
        {
            //employe e = new employe();
            Session["Message"] = null;

            string x = Session["matricule"].ToString();

            // int x1 = int.Parse(x);


            var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p =>  (p.ValdationRH == "refuse" || p.ValidationN1 == "refuse" || p.ValidationN2 == "refuse")).OrderByDescending(news => news.DateDC).ToList();


            return View(demandeConge);

        }
        public ActionResult Encours()
        {
            //employe e = new employe();
            Session["Message"] = null;

            string x = Session["matricule"].ToString();

            // int x1 = int.Parse(x);


            var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p =>  (p.ValdationRH == "En cours" || p.ValidationN1 == "En cours" || p.ValidationN2 == "En cours")).OrderByDescending(news => news.DateDC).ToList();


            return View(demandeConge);

        }

        public ActionResult MyChart()
        {  
            DateTime jD = Convert.ToDateTime(DateTime.Now.ToString("01/01/yyyy"));
            DateTime jF = Convert.ToDateTime(DateTime.Now.ToString("31/01/yyyy"));

            DateTime FD = Convert.ToDateTime(DateTime.Now.ToString("01/02/yyyy"));
            DateTime FF = Convert.ToDateTime(DateTime.Now.ToString("28/02/yyyy"));

            DateTime MarsD = Convert.ToDateTime(DateTime.Now.ToString("01/03/yyyy"));
            DateTime MarsF = Convert.ToDateTime(DateTime.Now.ToString("31/03/yyyy"));

            DateTime AD = Convert.ToDateTime(DateTime.Now.ToString("01/04/yyyy"));
            DateTime AF = Convert.ToDateTime(DateTime.Now.ToString("30/04/yyyy"));

            DateTime MD = Convert.ToDateTime(DateTime.Now.ToString("01/05/yyyy"));
            DateTime MF = Convert.ToDateTime(DateTime.Now.ToString("31/05/yyyy"));

            DateTime juD = Convert.ToDateTime(DateTime.Now.ToString("01/06/yyyy"));
            DateTime juF = Convert.ToDateTime(DateTime.Now.ToString("30/06/yyyy"));

            DateTime julD = Convert.ToDateTime(DateTime.Now.ToString("01/07/yyyy"));
            DateTime julF = Convert.ToDateTime(DateTime.Now.ToString("31/07/yyyy"));


            DateTime AoutD = Convert.ToDateTime(DateTime.Now.ToString("01/08/yyyy"));
            DateTime AoutF = Convert.ToDateTime(DateTime.Now.ToString("31/08/yyyy"));


            DateTime sepD = Convert.ToDateTime(DateTime.Now.ToString("01/09/yyyy"));
            DateTime sepF = Convert.ToDateTime(DateTime.Now.ToString("30/09/yyyy"));

            DateTime OcD = Convert.ToDateTime(DateTime.Now.ToString("01/10/yyyy"));
            DateTime OcF = Convert.ToDateTime(DateTime.Now.ToString("31/10/yyyy"));

            DateTime novD = Convert.ToDateTime(DateTime.Now.ToString("01/11/yyyy"));
            DateTime novF = Convert.ToDateTime(DateTime.Now.ToString("30/11/yyyy"));

            DateTime DEcD = Convert.ToDateTime(DateTime.Now.ToString("01/12/yyyy"));
            DateTime  DecF = Convert.ToDateTime(DateTime.Now.ToString("31/12/yyyy"));


            string[] xv = { "janvier", "Février", "Mars", "Avril", "May", "juin" , "juillet" , "Aout" , "September" , "October" , "November","December"};
           


            //Les demandes non traiter
         
          var NT1 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= jD && p.DateFin <= jF).Count();
            var NT2 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= FD && p.DateFin <= FF).Count();
            var NT3 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= MarsD && p.DateFin <= MarsF).Count();
            var NT4 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= AD && p.DateFin <= AF).Count();
            var NT5 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= MD && p.DateFin <= MF).Count();
            var NT6 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= juD && p.DateFin <= juF).Count();
            var NT7 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= julD && p.DateFin <= julF).Count();

            var NT8 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= AoutD && p.DateFin <= AoutF).Count();
            var NT9 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= sepD && p.DateFin <= sepF).Count();
            var NT10 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >=OcD && p.DateFin <= OcF).Count();
            var NT11 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= novD && p.DateFin <= novF).Count();
            var NT12 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= DEcD && p.DateFin <= DecF).Count();


            //Accepte

            var A1 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "accepte" && p.DateDebut >= jD && p.DateFin <= jF).Count();
            var A2 = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "accepte" && p.DateDebut >= FD && p.DateFin <= FF).Count();

Areas/Admin/Views/Dashb1/Index.cshtml
@model IEnumerable<GestionAbscences.Data.entite>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.bundle.min.js"></script>
</head>
<body class="sb-nav-fixed">




    <main>
      

        <div class="container-fluid" style="margin-top:15px;">


            <div class="row">

                <!-- /global -->
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body d-flex align-items-center justify-content-between " style="height:20px; font-weight:bold;">
                            <a class=" text-white stretched-link" href="@Url.Action("Global", "DashB1")">Demande de Congé</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>

                        </div>
                        <div class="card-footer" style="height:70px;">
                            <div style="font-weight:bold;">
                                100%
                            </div>
                            <div>
                                @Session["global"]
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /EnCours-->

                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body d-flex align-items-center justify-content-between " style="height:20px; font-weight:bold;">
                            <a class=" text-white stretched-link" href="@Url.Action("Encours", "DashB1")">Demande en attente </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>

                        </div>
                        <div class="card-footer" style="height:70px;">
                            <div style="font-weight:bold;">
                                @Session["enCours1"]%
                            </div>
                            <div>
                                @Session["enCours"]
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /accepte -->

                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body d-flex align-items-center justify-content-between " style="height:20px; font-weight:bold;">
                            <a class=" text-white stretched-link" href="@Url.Action("Accepte", "DashB1")">Demande Accepté </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>

                        </div>
                        <div class="card-footer" style="height:70px;">
                            <div style="font-weight:bold;">
                                @Session["accept1"]%
                            </div>
                            <div>
                                @Session["accepte"]
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /Refuse-->

                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body d-flex align-items-center justify-content-between " style="height:20px; font-weight:bold;">
                            <a class=" text-white stretched-link" href="@Url.Action("Refuse", "DashB1")">Demande Refusé </a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>

                        </div>
                        <div class="card-footer" style="height:70px;">
                            <div style="font-weight:bold;">
                                @Session["refuse1"]%
                            </div>
                            <div>
                                @Session["refuse"]
                            </div>
                        </div>
                    </div>
                </div>

                @Session["name"]


                <div class="card card-success col-12">
                    <div class="card-header">
                        <h3 class="card-title">Demande de congé</h3>


                    </div>
                    <div class="card-body ">
                        <div class="chart">
                            <img src="@Url.Action("MyChart" , "Dashb1")">
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>

                <div class="card card-success col-12">

                    <div class="card-body ">
                        <div class="chart">
                            <img src="@Url.Action("MyLine" , "Dashb1")">
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>

                <div class="card card-success col-12">

                    <div class="card-body ">
                        <div class="chart">
                            <img src="@Url.Action("Pie1" , "Dashb1")">
                            <img src="@Url.Action("Pie2" , "Dashb1")">

                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>



                <!-- jQuery -->
                <script src="~/Scripts/jquery-3.4.1.min.js"></script>
                <!-- Bootstrap 4 -->
                <!-- ChartJS -->
                <script src="~/Scripts/Chart.min.js"></script>

                <!-- AdminLTE for demo purposes -->
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/datatables-demo.js"></script>
</body>
</html>