Models/typeConge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GestionAbscences.Models
{
    public class typeConge
    {
        public int ID { get; set; }
        public int designation { get; set; }
    }
}

Areas/RH/Controllers/typecongesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionAbscences.Data;

namespace GestionAbscences.Areas.RH.Controllers
{
    public class typecongesController : Controller
    {
        private GestionAbscencesEntities11 db = new GestionAbscencesEntities11();

        // GET: RH/typeconges
        public ActionResult Index()
        {
            // typeconge t = new typeconge();
            var t = db.typeconge;
            foreach (var item in t)
            {
                if (item.idtypeConge == 1)
                {
                    ViewBag.t1 = item.dureeJ;
                }
                if (item.idtypeConge == 2)
                {
                    ViewBag.t2 = item.dureeJ;
                }
                if (item.idtypeConge == 3)
                {
                    ViewBag.t3 = item.dureeJ;
                }


                if (item.idtypeConge == 4)
                {
                    ViewBag.t4 = item.dureeJ;
                }
                if (item.idtypeConge == 5)
                {
                    ViewBag.t5 = item.dureeJ;
                }
                if (item.idtypeConge == 6)
                {
                    ViewBag.t6 = item.dureeJ;
                }


               
                if (item.idtypeConge == 9)
                {
                    ViewBag.t9 = item.dureeJ;
                }


                
                if (item.idtypeConge == 11)
                {
                    ViewBag.t11 = item.dureeJ;
                }
                if (item.idtypeConge == 12)
                {
                    ViewBag.t12 = item.dureeJ;
                }


                if (item.idtypeConge == 13)
                {
                    ViewBag.t13 = item.dureeJ;
                }
                if (item.idtypeConge == 14)
                {
                    ViewBag.t14 = item.dureeJ;
                }
                if (item.idtypeConge == 15)
                {
                    ViewBag.t15 = item.dureeJ;
                }

               
                  if (item.idtypeConge == 7)
                {
                    ViewBag.t7 = item.dureeJ;
                }
                if (item.idtypeConge == 8)
                {
                    ViewBag.t8 = item.dureeJ;
                }
                  if (item.idtypeConge == 10)
                {
                    ViewBag.t10 = item.dureeJ;
                }


                /*
              if (item.idtypeConge == 16)
              {
                  ViewBag.t16 = item.dureeJ;
              }
              if (item.idtypeConge == 17)
              {
                  ViewBag.t17 = item.dureeJ;
              }
              if (item.idtypeConge == 18)
              {
                  ViewBag.t18 = item.dureeJ;
              }

              if (item.idtypeConge == 19)
              {
                  ViewBag.t19 = item.dureeJ;
              }

              */
                if (item.idtypeConge == 20)
                {
                    ViewBag.t20 = item.dureeJ;
                }
                if (item.idtypeConge == 21)
                {
                    ViewBag.t21 = item.dureeJ;
                }



                if (item.idtypeConge == 22)
                {
                    ViewBag.t22 = item.dureeJ;
                }



            }

            return View(t.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modifier()
        {
           

            typeconge a1= db.typeconge.Find(1);
            a1.dureeJ = Request["x1"];
            db.Entry(a1).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a2 = db.typeconge.Find(2);
            a2.dureeJ = Request["x2"];
            db.Entry(a2).State = EntityState.Modified;
            db.SaveChanges();
            // 
            typeconge a3= db.typeconge.Find(3);
            a3.dureeJ = Request["x3"];
            db.Entry(a3).State = EntityState.Modified;
            db.SaveChanges();
            // 
            typeconge a4= db.typeconge.Find(4);
            a4.dureeJ = Request["x4"];
            db.Entry(a4).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a5 = db.typeconge.Find(5);
            a5.dureeJ = Request["x5"];
            db.Entry(a5).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a6 = db.typeconge.Find(6);
            a6.dureeJ = Request["x6"];
            db.Entry(a6).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a7 = db.typeconge.Find(7);
            a7.dureeJ = Request["x6"];
            db.Entry(a7).State = EntityState.Modified;
            db.SaveChanges();
            // 
            typeconge a8 = db.typeconge.Find(8);
            a8.dureeJ = Request["x6"];
            db.Entry(a8).State = EntityState.Modified;
            db.SaveChanges();
            //

            typeconge a9 = db.typeconge.Find(9);
            a9.dureeJ = Request["x9"];
            db.Entry(a9).State = EntityState.Modified;
            db.SaveChanges();
            //

            typeconge a10 = db.typeconge.Find(10);
            a10.dureeJ = Request["x9"];
            db.Entry(a10).State = EntityState.Modified;
            db.SaveChanges();

            typeconge a11 = db.typeconge.Find(11);
            a11.dureeJ = Request["x11"];
            db.Entry(a11).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a12 = db.typeconge.Find(12);
            a12.dureeJ = Request["x12"];
            db.Entry(a12).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a13 = db.typeconge.Find(13);
            a13.dureeJ = Request["x13"];
            db.Entry(a13).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a14 = db.typeconge.Find(14);
            a14.dureeJ = Request["x14"];
            db.Entry(a14).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a15 = db.typeconge.Find(15);
            a15.dureeJ = Request["x15"];
            db.Entry(a15).State = EntityState.Modified;
            db.SaveChanges();
            /*
            typeconge a16 = db.typeconge.Find(16);
            a16.dureeJ = Request["x16"];
            db.Entry(a16).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a17 = db.typeconge.Find(17);
            a17.dureeJ = Request["x17"];
            db.Entry(a17).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a18 = db.typeconge.Find(18);
            a18.dureeJ = Request["x18"];
            db.Entry(a18).State = EntityState.Modified;
            db.SaveChanges();
            //
            typeconge a19 = db.typeconge.Find(19);
            a19.dureeJ = Request["x19"];
            db.Entry(a19).State = EntityState.Modified;
            db.SaveChanges();
            
            //
            */
            typeconge a21 = db.typeconge.Find(21);
            a21.dureeJ = Request["x20"];
            db.Entry(a21).State = EntityState.Modified;
            db.SaveChanges();

            typeconge a20 = db.typeconge.Find(20);
            a20.dureeJ = Request["x20"];
            
            db.Entry(a20).State = EntityState.Modified;
            db.SaveChanges();
            //
          
            typeconge a22 = db.typeconge.Find(22);
            a22.dureeJ = Request["x22"];
            db.Entry(a22).State = EntityState.Modified;
            db.SaveChanges();
            //








            return RedirectToAction("Index");
        }

        // GET: RH/typeconges/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            typeconge typeconge = db.typeconge.Find(id);
            if (typeconge == null)
            {
                return HttpNotFound();
            }
            return View(typeconge);
        }

        // GET: RH/typeconges/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RH/typeconges/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idtypeConge,designation,dureeJ")] typeconge typeconge)
        {
            if (ModelState.IsValid)
            {
                db.typeconge.Add(typeconge);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(typeconge);
        }

        // GET: RH/typeconges/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            typeconge typeconge = db.typeconge.Find(id);
            if (typeconge == null)
            {
                return HttpNotFound();
            }
            return View(typeconge);
        }

        // POST: RH/typeconges/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Areas/RH/Views/typeconges/Create.cshtml
@model GestionAbscences.Data.typeconge

@{
    ViewBag.Title = "Ajouter un type de congé";
}

<h2></h2>
<title>Ajouter un type de congé </title>

<div class="container">
    <br>    

    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card shadow-lg border-0 rounded-lg mt-0 " style="margin-right:120px;margin-top:10px; margin-left:120px;height:auto;">

                <div class="card-header " style="background-color:#EFEFEF;  padding:10px;"><h2 class="text-center font-weight-bold my-0">Ajouter un type de congé </h2></div>

                <br>    <br>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <div class="row align-items-start">
                                <div class="col-3" style="padding-left: 60px; font-weight: bold;">
                                    Designation
                                </div>
                                <div class="col-8">
                                    @Html.EditorFor(model => model.designation, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.designation, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row align-items-start">
                                <div class="col-3" style="padding-left:60px; font-weight:bold;">
                                    Durée
                                </div>
                                <div class="col-8">
                                    @Html.EditorFor(model => model.dureeJ, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.dureeJ, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>


                        <br>


                        <div class="form-group">
                            <div class="row align-items-start">
                                <div class="col-5">
                                </div>
                                <div class="col-4">

                                    <input type="submit" value="Ajouter" class="btn btn-success" style="padding-left:60px; padding-right:60px;">

                                </div>
                            </div>
                        </div>
                        <br />



                    </div>
                }

                <div style="margin-left:100px;">
                    @Html.ActionLink("Retour à la liste ", "Index")

                </div>

                <br>    <br>

            </div>
        </div>
    </div>
</div>

Areas/RH/Views/typeconges/Delete.cshtml
@model GestionAbscences.Data.typeconge

@{
    ViewBag.Title = "Delete";

}



<div>
    <br />
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card shadow-lg border-0 rounded-lg mt-0 " style="margin-right:180px;margin-top:10px; margin-left:180px;height:auto;">

                    <div class="card-header " style="background-color:#EFEFEF;  padding:10px;"><h4 class="text-center font-weight-bold my-0">Êtes-vous sûr de vouloir le supprimer?</h4></div>


                    <br />
                    <div class="form-group">

                        <table class="table table-light table-striped" style="margin-left:60px;margin-right:30px; width:590px; margin-top:10px;">
                            <tr>
                                <td style="font-weight:bold; ">
                                    Designation
                                </td>
                                <td>
                                    @Model.designation
                                </td>


                            </tr>
                            <tr>
                                <td style="font-weight:bold; ">
                                    Durée
                                </td>
                                <td>
                                    @Model.dureeJ
                                </td>


                            </tr>
                        </table>

                    </div>



                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <br>


                        <div class="form-group">
                            <div class="row align-items-start">
                                <div class="col-4">
                                </div>
                                <div class="col-6">

                                    <input type="submit" value="Supprimer" class="btn btn-warning" style="padding-left:50px; padding-right:50px;">

                                </div>
                            </div>
                        </div>
                        <br />


                    }

                    <div style="margin-left:100px;">
                        @Html.ActionLink("Retour à la liste ", "Index")

                    </div>

                    <br>    <br>
                </div>

            </div>
        </div>
    </div>
</div>   

Areas/RH/Views/typeconges/Details.cshtml
@model GestionAbscences.Data.typeconge

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>typeconge</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dureeJ)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dureeJ)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idtypeConge }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/RH/Views/typeconges/Edit.cshtml
@model GestionAbscences.Data.typeconge

@{
    ViewBag.Title = "Modifier";

}


    <div class="container">
        <br>

        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card shadow-lg border-0 rounded-lg mt-0 " style="margin-right:120px;margin-top:10px; margin-left:120px;height:auto;">

                    <div class="card-header " style="background-color:#EFEFEF;  padding:10px;"><h2 class="text-center font-weight-bold my-0">Modifier un type de congé </h2></div>

                    <br>    <br>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.idtypeConge)

                    <div class="form-group">
                        <div class="row align-items-start">
                            <div class="col-3" style="padding-left: 60px; font-weight: bold;">
                                Designation
                            </div>
                            <div class="col-8">
                                @Html.EditorFor(model => model.designation, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.designation, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row align-items-start">
                            <div class="col-3" style="padding-left:60px; font-weight:bold;">
                                Durée
                            </div>
                            <div class="col-8">
                                @Html.EditorFor(model => model.dureeJ, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.dureeJ, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>


                    <br>


                    <div class="form-group">
                        <div class="row align-items-start">
                            <div class="col-5">
                            </div>
                            <div class="col-4">

                                <input type="submit" value="Enregistrer" class="btn btn-success" style="padding-left:60px; padding-right:60px;">

                            </div>
                        </div>
                    </div>
                    <br />

                   
                </div>
                    }

                    <div style="margin-left:100px;">
                        @Html.ActionLink("Retour à la liste ", "Index")

                    </div>
                    <br>    <br>

                </div>
            </div>
        </div>
    </div>

Areas/RH/Views/typeconges/Index.cshtml
@model IEnumerable<GestionAbscences.Data.typeconge>

@{
    ViewBag.Title = "Paramètre : type de congé";

}


<title> Paramètre : type de congée </title>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
   
    <title>Paramètre : type de congé</title>
    
    
  
</head>
@using (Html.BeginForm("Modifier", "typeconges", FormMethod.Post))

{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <body >



        <div class="card mb-4">
            <div class="card-header" style="font-size:large ; " >
                <i class="fas fa-table mr-1"></i>
                Paramètre : type de congé
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" width="100%" cellspacing="0">

                        <thead>
                            <tr class="table-success">
                                <th style="text-align:center;">
                                    Designation
                                </th>
                                <th style="text-align:center;">
                                    Durée
                                </th>

                            </tr>
                        </thead>

                        <tfoot>

                        </tfoot>
                        <tbody>



                            <tr>
                                <td style="text-align:center;">
                                    1ere Tranche      <span style="text-align:center; font-weight:bold; padding-left:20px;">  >= </span>
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x1" id="x1" value="@ViewBag.t1" style="width:100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    2eme Tranche            <span style="text-align:center; font-weight:bold; padding-left:20px;">  >= </span>
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x2" id="x2" value="@ViewBag.t2" style="width: 100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Reliquat
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x3" id="x3" value="@ViewBag.t3" style="width: 100%;" />

                                </td>
                            </tr>

                            <tr>
                                <td style="text-align:center;">
                                    Mariage du salarié
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x4" id="x4" value="@ViewBag.t4" style="width:100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Mariage d'un enfant du salarié
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x5" id="x5" value="@ViewBag.t5" style="width: 100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Décès: (parents-d'un enfant-d'un conjoint)  du salarié
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x6" id="x6" value="@ViewBag.t6" style="width: 100%;" />

                                </td>
                            </tr>


                            <tr>
                                <td style="text-align:center;">
                                    Décès : d'un frère ou d'une soeur du  : salarié-conjoint
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x9" id="x9" value="@ViewBag.t9" style="width: 100%;" />

                                </td>
                            </tr>


                            <tr>
                                <td style="text-align:center;">
                                    Exceptionnel/CR : 1/2 journée
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x11" id="x11" value="@ViewBag.t11" style="width: 100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Exceptionnel/CR : 1 journée
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x12" id="x12" value="@ViewBag.t12" style="width: 100%;" />

                                </td>
                            </tr>

                            <tr>
                                <td style="text-align:center;">
                                    Exceptionnel/CR : 1.5 journée
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x13" id="x13" value="@ViewBag.t13" style="width:100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Exceptionnel/CR : 2 journée
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x14" id="x14" value="@ViewBag.t14" style="width: 100%;" />

                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center;">
                                    Circoncision
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x15" id="x15" value="@ViewBag.t15" style="width: 100%;" />

                                </td>
                            </tr>

                            <tr>
                                <td style="text-align:center;">
                                    Opération chirurgicale : du conjoint-d'un enfant à charge
                                </td>
                                <td style="text-align:center;">
                                    <input type="text" name="x20" id="x20" value="@ViewBag.t20" style="width:100%;" />

                                </td>
                            </tr>

                              <tr>
            <td style="text-align:center;">
                Naissance
            </td>
            <td style="text-align:center;">
                <input type="text" name="x22" id="x22" value="@ViewBag.t22" style="width: 100%;" />

            </td>
        </tr>
                            





                        </tbody>

                    </table>

                </div>
                <br>
                <div class="offset-5  ">
                <button class="btn btn-warning" style="padding-left:60px; padding-right:60px;">Enregistrer</button>
                <br>

                </div>
                <br />

            </div>
        </div>


       

    </body>
}
</html>