Areas/RH/Controllers/AnnulerController.cs
using GestionAbscences.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using GestionAbscences.Services;
using GestionAbscences.Areas.Admin.Models;
using System.Net;
using System.IO;
using System.Data;
using ClosedXML.Excel;
namespace GestionAbscences.Areas.RH.Controllers
{
    public class AnnulerController : Controller
    {
        private GestionAbscencesEntities11 db = new GestionAbscencesEntities11();
        private readonly DemandeService demandeService;

        public AnnulerController()
        {
            demandeService = new DemandeService();
        }

        // GET: RH/Annuler
        public ActionResult Index()
        {
            var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValdationRH == "accepte" && p.ValidationN2 == "accepte").OrderByDescending(news => news.DateDC).ToList();

            return View(demandeConge);

        }




        public ActionResult Annulation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var currentDemande = demandeService.ReadById(id.Value);
            if (currentDemande == null)
            {
                return HttpNotFound($"this demande ({id}) is not found");
            }


            demandeconge demandeconge = db.demandeconge.Find(id);
            Session["uid"] = currentDemande.idDemandeConge;

            if (demandeconge == null)
            {
                return HttpNotFound();
            }

            return View(demandeconge);
        }

        //filtrage
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult choixVal1()
        {
            string d1 = Request["debut"].ToString();
            string f1 = Request["fin"].ToString();
            ViewBag.d2 = Request["debut"].ToString();
            ViewBag.f2 = Request["fin"].ToString();


            string val = Request["validation"].ToString();



            if (d1.Equals("") || f1.Equals("") || val.Equals(""))
            {
                ViewBag.message = "Selectionner les dates et la catégorie svp !";
                return RedirectToAction("historique");
            }
            else
            {
                DateTime debut = Convert.ToDateTime(Request["debut"]);

                DateTime fin = Convert.ToDateTime(Request["fin"]);

                if (val.Equals("1"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("2"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "En cours" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("3"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "accepte" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("4"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN1 == "refuse" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("5"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN2 == "En cours" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("6"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN2 == "accepte" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("7"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValidationN2 == "refuse" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("8"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValdationRH == "En cours" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("9"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValdationRH == "accepte" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }
                else if (val.Equals("10"))
                {
                    var demandeConge = db.demandeconge.Include(d => d.employe).Include(d => d.typeconge).Where(p => p.ValdationRH == "refuse" && p.DateDebut >= debut && p.DateDebut <= fin).OrderByDescending(news => news.DateDC).ToList();
                    return View(demandeConge.ToList());
                }


            }


            return RedirectToAction("historique");

        }

        [HttpPost]
        public ActionResult Annulation()
        {
            int uid = int.Parse(Session["uid"].ToString());
            demandeconge e = db.demandeconge.Find(uid);
            string button = Request["button"];

            DateTime dateDebut = e.DateDebut.Value;
            DateTime dateFin = e.DateFin.Value;


            /*   var dure = (dateFin - dateDebut).Days;


               double du = Convert.ToDouble(dure) + 1;
               double d = du * 24;
               double nb = Convert.ToDouble(e.employe.nbHeureR);

               double res = nb + d;
            */

            int annee = Convert.ToInt32(DateTime.Now.ToString("yyyy"));
            int mois = Convert.ToInt32(DateTime.Now.ToString("MM"));

            var recup = db.CumulRecup.Include(d => d.employe).Where(p => p.employe.idEmploye == e.IdEmploye && p.Annee == annee && p.Mois == mois).Select(u => new {
                hs = u.CumulHr,
                jf = u.CumulJrF,
                jr = u.CumulJrR,
                id = u.IDCumulRecup

            }).Single();

            CumulRecup cr = db.CumulRecup.Find(recup.id);

            double hsA = Convert.ToDouble(cr.CumulHr);

            //en heure 
            double jf = Convert.ToDouble(recup.jf);


            double jR = Convert.ToDouble(recup.jr);



            var dureM = (dateFin - dateDebut).TotalHours ;
            var dureD = (dateFin - dateDebut).Days + 1;
            double duM = Convert.ToDouble(dureM);
            double nbM = Convert.ToDouble(e.employe.nbHeureR);
            double resM = nbM + duM;










            switch (button)
            {
                case "Retour":
                   
                    return RedirectToAction("Index");
                case "annule":
                    if (e.IdtypeConge == 23)
                    {
                        double dhs = hsA + dureM;
                        cr.CumulHr = Convert.ToString(dhs);
                        e.ValdationRH = "En cours";

                    }
                    else
                   if (e.IdtypeConge == 25)
                    {
                        double dhs = jf + dureD;
                        string dh = Convert.ToString(dhs);
                        cr.CumulJrF = float.Parse(dh);
                        e.ValdationRH = "En cours";
                    }
                    else
                   if (e.IdtypeConge == 24)
                    {
                        double dhs = jR + dureD;
                        string dh = Convert.ToString(dhs);
                        cr.CumulJrR = float.Parse(dh);
                        e.ValdationRH = "En cours";

                    }
                    else
                    if (e.IdtypeConge == 4 || e.IdtypeConge == 5 || e.IdtypeConge == 22 || e.IdtypeConge == 6 || e.IdtypeConge == 7 || e.IdtypeConge == 8 || e.IdtypeConge == 9 || e.IdtypeConge == 10 || e.IdtypeConge == 15 || e.IdtypeConge == 20 || e.IdtypeConge == 21)
                    {
                        e.ValdationRH = "En cours";
                    }
                    else
                    {
                        e.employe.nbHeureR = resM.ToString();
                        e.ValdationRH = "En cours";
                    }





                    
                    e.ValidationN1 = "En cours";
                    e.ValidationN2 = "En cours";
                    e.annulation = "oui";
                    db.Entry(e).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");

                default:
                    return View();

            }





        




    }

    }
}

Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionAbscences.Controllers
{
    public class DefaultController : BaseController
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

Areas/RH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="@Url.Action("Donnee","Account")">@Session["userName"] <br /> Mle : @Session["matricule"]</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
    @*    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">

            <div class="input-group">
                <div class="input-group-append">

                    <ul>
                        <li>
                            </br>


                            <a href="/Language/Frensh" style="color:antiquewhite;"><p class="p-2 mb-2  ">@GestionAbscences.Langagues.Resource1.Frensh</p></a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            </br>
                            <a href="/Language/English" style="color:antiquewhite;"><p class="p-2 mb-2 ">@GestionAbscences.Langagues.Resource1.English</p></a>

                        </li>
                    </ul>
                    <ul>
                        <li>
                            </br>

                            <a href="/Language/Arabic" style="color:antiquewhite;"><p class="p-2 mb-2 ">@GestionAbscences.Langagues.Resource1.Arabic</p></a>

                        </li>
                    </ul>
                </div>
            </div>
        </form>
        *@
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">

                    <a class="dropdown-item" href="@Url.Action("Donnée","Default")">Profil</a>

                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("Index","Login", new { area = "" })"> Déconnecter</a>


                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading"></div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>




                        @* <a class="nav-link" href="@Url.Action("Index","Employe")">
            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
            Employes
        </a>
                        *@

                        <a class="nav-link" href="@Url.Action("Index","typeconges")">
                            <div class="sb-nav-link-icon"><i class="fas fa-wrench"></i></div>
                            Paramètre
                        </a>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-file"></i></div>
                            Demande de congé
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("historique","Historique")"> <i class="fas fa-clock"></i>En attente </a>
                                <a class="nav-link" href="@Url.Action("Index","Annuler")"> <i class="fas fa-check"></i>   Accepté</a>
                            </nav>
                        </div>

                        <a class="nav-link" href="@Url.Action("Index","Employe")">
                            <div class="sb-nav-link-icon"><i class="fas fa-folder"></i></div>
                            Liste des employés
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","employehasentites")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Affectation
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","entites")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Entités
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Login")">
                           
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Déconnecter
                        </a>



                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Admin
                </div>
            </nav>
        </div>

        <div id="layoutSidenav_content">

            <div class="container-fluid">

                @RenderBody()
            </div>


        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/datatables-demo.js"></script>
</body>
</html>

Areas/RH/Views/Shared/_offlineLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Page Title - SB Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">

                    @RenderBody()
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>

</body>
</html>